import Head from 'next/head'
import Message  from '../components/Message'
import { useEffect, useState } from 'react'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        <Message/>
      </div>
    </div>
  )
}
